
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '9F4DA7C990A8E1D01A291B7D43B103AB'
    
_lr_action_items = {'num':([0,4,],[2,2,]),'subs':([2,3,5,],[-2,4,4,]),'$end':([1,2,3,5,],[0,-2,-1,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'E':([0,4,],[3,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> E','S',1,'p_g0','subtfinal.py',28),
  ('E -> num','E',1,'p_g1','subtfinal.py',31),
  ('E -> E subs E','E',3,'p_g2','subtfinal.py',36),
]
